title: kan01234 - Software Engineer Notes
author: kan01234
description: A backend engineer's journey of learning and growth.
logo: assets/logo.avif
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

categories:
- key: infra
  title: ğŸ§± Infrastructure & Platform Engineering
- key: monitoring
  title: ğŸ“Š Monitoring & Observability
- key: coding
  title: ğŸ§  Software Engineering Best Practices & Concepts
- key: system-design
  title: ğŸ“ System Design & Distributed Systems
- key: network
  title: ğŸ” Web & Network Protocols
- key: person
  title: âœ¨ Personal/Company Journey
